# Generated by Django 5.2.5 on 2025-10-07 19:16

import django.core.validators
import django.db.models.deletion
import gerencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('razao_social', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[gerencia.models.validar_cnpj, django.core.validators.MinLengthValidator(14, 'CNPJ deve conter exatamente 14 dígitos numéricos.')])),
                ('inscricao_municipal', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('inscricao_estadual', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('Ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'Telefone deve conter 10 dígitos numéricos (DDD + número!).')])),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='gerencia.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradoro', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('municipio', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, validators=[django.core.validators.MinLengthValidator(2, 'UF deve conter exatamente 2 letras.')])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8, 'CEP deve conter exatamente 8 dígitos numéricos.')])),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='gerencia.clientes')),
            ],
        ),
    ]
