# Generated by Django 5.2.5 on 2025-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=14, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('inscricao_minicipal', models.CharField(unique=True)),
                ('inscricao_estadual', models.CharField(unique=True)),
                ('logradoro', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
