# Generated by Django 5.2.5 on 2025-10-04 04:08

import django.core.validators
import django.db.models.deletion
import gerencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('razao_social', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[gerencia.models.validar_cnpj])),
                ('inscricao_minicipal', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('inscricao_estadual', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('Ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Telefone deve ter 10 dígitos (DDD + número).')])),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Telefone deve ter 10 dígitos (DDD + número).')])),
                ('whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='gerencia.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradoro', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('municipio', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='gerencia.clientes')),
            ],
        ),
    ]
